### ISSUE TITLE
Identifying current panel in JS inside bar panel

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tracy#159]
Currently I am unaware of a simple way to identify current panel inside javascript inside bar panel. [Nextras Mail Panel](https://github.com/nextras/mail-panel) works around this issue by [generating custom unique id](https://github.com/nextras/mail-panel/blob/d0e3223eca2bc757e33bdbc86e27cbac62775434/src/MailPanel.latte#L45-L46). This however duplicates the job as unique ID is already generated by Tracy itself. However I haven't been able to find a way to access this information.

The native way to solve this problem in JS is to use [document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript). This however does NOT work due to how scripts inside panels are executed by Tracy.

**Comment by milo** [comment]
I needed to pass bar panel ID from PHP to JS too in https://github.com/nette/tracy/pull/47/files#diff-b4906320d76737dbe766d42ab4b753f3R36.

**Comment by dg** [comment]
How to solve it?

**Comment by JanTvrdik** [comment]
I don't know. We can probably always set some global variable (such as `window.Tracy.currentScript`). Unfortunately `document.currentScript` is readonly so we cannot use that.

**Comment by milo** [comment]
Maybe some data attribute or html id for rendered bar panel element?

**Comment by JanTvrdik** [comment]
How would that help? Or mean that you would „move“ the id attribute from one script to another.

**Comment by milo** [comment]
Oh, I misunderstand the issue. I didn't know that Tracy already [renders the HTML ID](https://github.com/nette/tracy/blob/805f79732b7d6fa0921889c5492144840ec7cd3a/src/Tracy/assets/Bar/panels.phtml#L20).

When `currentScript` does not work...
```php
public function getPanel()
{
	$i = uniqid('panel-script');
	return "
		<h1>Panel</h1>
		<div>Content</div>
		<script id='$i'>
			console.log(document.getElementById('$i').parentNode.id);
		</script>
	";
}
```
And parse it from HTML ID. Because HTML ID [is sanitized](https://github.com/nette/tracy/blob/6306d26e7aea57c0bedffb6b31cd82bb2f5d7ece/src/Tracy/Bar.php#L84), some `data-` attribute may be proper.

Actually it solves my issue :) Hope I understand yours...
