### ISSUE TITLE
improveException should suggest installing missing extensions

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tracy#221]
For example [Call to undefined function Nette\Mail\finfo_buffer](https://forum.nette.org/cs/27067-call-to-undefined-function-nette-mail-finfo-buffer), should be improved to 

> Call to undefined function Nette\Mail\finfo_buffer, you need to enable finfo extension in php.ini

We obviously can't have a large array with all possible php functions, but having a simple array mapping function prefix to extension name should work well enough for most use-cases.

---

@dg If you think this would be useful, you may [tag this issue as easy pick](https://seld.be/notes/encouraging-contributions-with-the-easy-pick-label) to encourage contributions.

**Comment by CZechBoY** [comment]
+multibyte + disabled move_uploaded_file function etc.

**Comment by kravcik** [comment]
I guess everybody should run [https://doc.nette.org/cs/2.4/requirements#toc-requirements-checker](checker) before start working. So this feature will be obsolete.

**Comment by JanTvrdik** [comment]
@kravcik no, requirements checker solves different issue and does not help people who use Tracy without other Nette libraries

**Comment by dg** [comment]
IMHO the most confusing is namespace `Nette\Mail\`, it can be removed using `\finfo_buffer` or `use function finfo_buffer`. 

The problem only applies to extension fileinfo in nette/http and nette/mail and these extensions in [Latte](https://github.com/nette/latte/blob/fec7bd4a393e95e9521c7a1b595ec084eea9a4f8/composer.json#L26-L30) and [utils](https://github.com/nette/utils/blob/47dc56356a3ad2ce0af8a1ac57f5cae87201c2db/composer.json#L23-L30). Some of them are checked in code, some checks can be added. I am :-1: to solve it in Tracy.

**Comment by JanTvrdik** [comment]
> The problem only applies to extension 

I did not intended this feature for PHP extensions used by Nette but for all commonly missing PHP extensions such as json, curl, mbstring, openssl, ...

**Comment by dg** [comment]
As a general solution it probably makes sense.

BTW https://bugs.php.net/bug.php?id=73049

**Comment by Majkl578** [comment]
Probably good idea in general, but the message should be more generic (i.e. not mention php.ini) and work not only with extension-related functions (i.e. new/removed core function like set_magic_quotes_runtime()).

> BTW https://bugs.php.net/bug.php?id=73049

I believe the message is correct (although confusing), since the lookup is namespace-local first, then global. Same for constants. Maybe it could mention both variants in th message but either is partially _correct_.

**Comment by JanTvrdik** [comment]
> not mention php.ini

Why not mention php.ini? Can you post an example of how such message should look like according to you?

> work not only with extension-related functions

That seems out-of scope.

> I believe the message is correct (although confusing)

Have you read the bug report? Because that's exatly what is states.

**Comment by Majkl578** [comment]
> Can you post an example of how such message should look like according to you?

_Call to undefined function Nette\Mail\finfo_buffer or \finfo_buffer, ensure that finfo extension is enabled and loaded._

or maybe even like this to avoid namespace confusion:
_Call to undefined function finfo_buffer from namespace Nette\Mail, ensure that finfo extension is enabled and loaded._

> Have you read the bug report? Because that's exatly what is states.

Yes and it does not. Quoting:

_The better message should be "Call to undefined function json_encode()"._

It drops the information about namespace entirely (so if you were using e.g. namespaced function like from GuzzleHttp or [libsodium](https://paragonie.com/book/pecl-libsodium/read/01-quick-start.md#function-index), you would have hard time to figuring that out, because function is not prefixed by extension name).

**Comment by dg** [comment]
> would have hard time to figuring that out

There is file name and line number.

**Comment by JanTvrdik** [comment]
> Call to undefined function Nette\Mail\finfo_buffer or \finfo_buffer, ensure that finfo extension is enabled and loaded.

But we can know for sure ([extension_loaded](https://secure.php.net/manual/en/function.extension-loaded.php)) whether the extension is loaded. There is no need for the user to check whether the extension is loaded – we know it is not.

> Yes and it does not. Quoting:

You have said „I believe the message is correct (although confusing)“ and @dg has said „the error message (…) is (…) confusing.“ and „both error messages are correct“

**Comment by dg** [comment]
For message `Call to undefined function (namespace\)?(prefix)_.*` when prefix is one of the listed prefixes and correspoding extension is not loaded, ideal message is `Call to undefined function finfo_buffer, you need to enable finfo extension`, i.e. without namespace. I am not sure about `php.ini`.
