### ISSUE TITLE
Sql queries

### ISSUE THREAD

**Issue by Brakkar** [nette/tracy#243]
Hello,
i'm using PDO, no orm for my sql queries.
Is it possible for the toolbar to show the queries ?

I don't see them with the default install.

**Comment by Northys** [comment]
@Brakkar by default tracy has panel to show queries made by nette/database. There is also panel for dibi/dibi package. Check https://componette.com. I think it is not possible to show queries made by PDO without wrapper which would log it to the panel. Such wrapper is dibi for example.

**Comment by jtojnar** [comment]
Simple wrapper: https://github.com/filisko/pdo-plus

**Comment by patrickkusebauch** [comment]
@jtojnar It was not an issue at the time, but now with PHP7 it is. This package will not work where parameter types are enforced at the moment since the wrapper's `PDOStatement` does not extend the extension `PDOStatement`. Therefore if you use this library somewhere where you use the `PDOStatement` as a parameter type. This package will fail at the moment.
