### ISSUE TITLE
Link callstack in bluescreen

### ISSUE THREAD

**Issue by BernhardBaumrock** [nette/tracy#354]
Hello everybody and thx for your awesome tools! I'm using TracyDebugger on ProcessWire and thought it would be great to have the bluescreen callstack linked to the corresponding file + line so that we can click on it and open it up in our IDE just like it is already implemented in all the other panels.

I'm talking about this screen:
![img](https://i.imgur.com/pTzP09b.png)

Could all those items in the list be linked?

Thx in advance!

**Comment by dg** [comment]
It is related to this https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/index.php#L63-L64.

Instead of an exception with all the information, it throws a error where the callstack is serialized in message, so Tracy cannot display it. Would @adrianbj know why this is happening?

**Comment by adrianbj** [comment]
Good catch @dg - I'd never really got around to figuring out why ProcessWire was messing with exceptions.

I removed that`trycatch` in ProcessWire's index.php and everything is now reported correctly and the stack trace is broken out and all linked. I'll see what I can do about getting a change made to the PW core to fix this.

@BernhardBaumrock - I think this can be closed and I'll follow up with an Issue in the PW repo.

**Comment by adrianbj** [comment]
@BernhardBaumrock - new issue on PW repo: https://github.com/processwire/processwire-issues/issues/829 if you'd like to your support, or a comment.
