### ISSUE TITLE
Wrong IP address in info panel

### ISSUE THREAD

**Issue by petrparolek** [nette/tracy#416]
Version: 2.7.4

### Bug Description
![obrazek](https://user-images.githubusercontent.com/6066243/79371572-e12ca000-7f54-11ea-89fd-a578749d83e4.png)

I tested standalone Tracy on Vagrant / Laravel Homestead.

### Expected Behavior
![obrazek](https://user-images.githubusercontent.com/6066243/79371599-e853ae00-7f54-11ea-9129-a1a82e935a53.png)

### Possible Solution
revert commit ce31ae5d5d92709d8624b4ee0f46cd9f16aa7c1e

**Comment by dg** [comment]
cc @janbarasek

**Comment by janbarasek** [comment]
@dg @petrparolek I am not sure which solution is ok.

In case of production server is this behavior ok, because function `php_uname('n')` return `homestead` and `gethostbyname()` return `127.0.1.1` (what is not good IP address).

But in case of production server, function `gethostbyname()` should return real IP address by reverse DNS check.

## Possible solution

Tracy should detect current environment and in case of local environment use old IP detection method by `$_SERVER['SERVER_ADDR']`.

**Comment by petrparolek** [comment]
what do you @dg @janbarasek think about my solution in #417 ?

**Comment by janbarasek** [comment]
@petrparolek I'm not sure your solution is safe. The IP address through the proxy may be spoofed.

See my article for more information (czech language): https://php.baraja.cz/ip-adresa

First you should fix your failing tests: https://travis-ci.org/github/nette/tracy/builds/675458839

Thanks.

**Comment by petrparolek** [comment]
thx
